# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: SecondWF

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CI: true
    - name: npm install
      run: |
          make install
    - name: Run linter
      run: |
          make lint
        
    - name: Test & publish code coverage
    
      uses: paambaati/codeclimate-action@v2.6.0
      
      with:
          coverageCommand: make test-coverage
          debug: true
